apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ashutoshcluster1
  region: ap-south-1

nodeGroups:
  - name: nodegroup1
    desiredCapacity: 2
    instanceType: t2.micro
    ssh:
        publicKeyName: key
  - name: nodegroup2
    desiredCapacity: 2
    instanceType: t2.small
    ssh:
        publicKeyName: key
  - name: ngmixed
    minSize: 3
    maxSize: 4
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3.small", "t3.medium"] 
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    ssh:
        publicKeyName: key 
  
